[[plugins]]
repo = "Shougo/ddu.vim"

[[plugins]]
repo = "Shougo/ddu-ui-ff"

[[plugins]]
repo = "Shougo/ddu-source-file_rec"

[[plugins]]
repo = "Shougo/ddu-filter-matcher_substring"

[[plugins]]
repo = "Shougo/ddu-kind-file"

